# Ansible Playbook for Subutai Elasticsearch Blueprint
--- 

- hosts: elasticsearch
  remote_user: root
  tasks:

    - debug: var=ansible_default_ipv4.address

    # -------------------------------------------------------------------------
    # Freshen up the host
    # -------------------------------------------------------------------------

    - name: Disable dpkg fsync
      raw: test -e /etc/dpkg/dpkg.cfg.d/unsafe-io || echo force-unsafe-io > /etc/dpkg/dpkg.cfg.d/unsafe-io

    - name: Upgrade packages
      apt:
        update_cache: true
        upgrade: true

    # -------------------------------------------------------------------------
    # Install shit that should be there and fix locales
    # -------------------------------------------------------------------------

    - name: Install setup tools
      apt:
        name: 
          - dirmngr
          - apt-transport-https
          - ca-certificates
          - sudo
          - locales
          - curl
          - default-jdk

    - name: Transfer locales_setup.sh
      copy: src=locales_setup.sh dest=/root/locales_setup.sh

    - name: Execute locales_setup.sh
      command: bash /root/locales_setup.sh

    # -------------------------------------------------------------------------
    # Elasticsearch User, Install, Configs
    # -------------------------------------------------------------------------

    - name: Create elasticsearch user
      user:
        name: elasticsearch
        password: "{{ subutai.user_variables.password }}"
        state: present
        shell: /bin/bash
        system: no
        createhome: yes
        home: /var/lib/elasticsearch

    - name: Download ES tarball
      get_url:
        url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.5.4.tar.gz
        dest: /root/elasticsearch-6.5.4.tar.gz
  
    - name: Create /usr/share/elasticsearch
      file:
        path: /usr/share/elasticsearch
        state: directory
        mode: 0755 

    - name: Untar elasticsearch tarball
      unarchive: 
        src: /root/elasticsearch-6.5.4.tar.gz
        dest: /usr/share/elasticsearch
        remote_src: yes
        extra_opts:
          - --strip-components=1
      
    # purposefully not using this elasticsearch_plugin 
    - name: Remove analysis-icu plugin
      command: /usr/share/elasticsearch/bin/elasticsearch-plugin remove analysis-icu
      ignore_errors: yes
    
    # purposefully not using this elasticsearch_plugin 
    - name: Install the analysis-icu plugin
      command: /usr/share/elasticsearch/bin/elasticsearch-plugin --silent install analysis-icu
    
    - name: Install the systemd initialization file
      copy:
        src: elasticsearch.service
        dest: /etc/systemd/system/elasticsearch.service

    - name: Install the configuration file
      copy:
        src: elasticsearch.yml
        dest: /etc/elasticsearch/

    - name: Massage elasticsearch.yml values
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: 'network.host: ${ES_NETORK_HOST}'
        line: "{{ ansible_default_ipv4.address }}"

    - name: Install the jvm.options file
      copy:
        src: jvm.options
        dest: /etc/elasticsearch/

    - name: Add environment configuration block
      blockinfile:
        path: /etc/environment
        block: |
          ES_PATH_CONF=/etc/elasticsearch
          ES_NETWORK_HOST={{ ansible_default_ipv4.address }}
          ES_JAVA_OPTS="-Xmx3g -Xms1g"

    - name:
      systemd:
        name: elasticsearch
        state: started
        enabled: yes
        daemon_reload: yes
    
    - name: wait for the app to come up
      wait_for:
        port: 9200
        host: "{{ ansible_default_ipv4.address }}"
        delay: 10
        timeout: 60

    - name:
      uri:
        url: http://{{subutai.user_variables.hostname}}:9200/api/plugins
        register: response
        failed_when: "'analysis-icu' not in response.content"
      retries: 3
      delay: 10
